server.port: 9001

spring:
  profiles.active: dev
  application:
    name: greeter-messages

eureka:        
  ## you can comment out all eureka config on TAS
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

  #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    # non-secure-port-enabled: true  # uncomment to use 'apps.internal' domain on TAS.
    # non-secure-port: 8080          # uncomment to use 'apps.internal' domain on TAS. do not uncomment on other env. it will chnage port 8080
    # secure-port-enabled: false     # uncomment to use 'apps.internal' domain on TAS.
    #secure-port:

    #hostname:
    #preferIpAddress: false

      
management:
  endpoints:
    web:
      exposure:
        include: '*'

#logging.level.root: debug