spring:
  application:
    name: my-cloud-native-spring
    profiles.active: dev
  config:
    import: configserver:http://localhost:8888
    #import: optional:configserver:http://localhost:8888
#    #import: configserver:${vcap.services.p-config-server.credentials.uri:http://localhost:8888}
  cloud:
    bootstrap:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: '*'

cook.special: "Kim Chi in cloud-native-spring app"