spring:
  application:
    name: cloud-native-spring
  profiles.active: dev

server.port: 8080

## you can comment out all eureka config on TAS
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.greeter-service-registry.credentials.uri:http://127.0.0.1:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'


cook.special: "Kim Chi in cloud-native-spring app"