spring:
  application:
    name: cloud-native-spring
  main:
    allow-bean-definition-overriding: true
  profiles.active: dev
  cloud:
    config:
      uri: ${vcap.services.my-config-server.credentials.uri:http://localhost:8888}
    
server.port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'


cook.special: "Kim Chi in cloud-native-spring app"