server.port: 9002

spring:
  application:
    name: greeter
    profiles.active: dev

## you can comment out all eureka config on TAS
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

#logging.level.root: debug