server.port: 8888
spring:
  cloud:
    config:
      name: configserver
      server.git:
        #uri: file:///Users/minseok/_dev/spring-cloud-sample-configrepo
        uri: https://github.com/myminseok/spring-cloud-sample-configrepo
        default-label: main
