server.port: 8080

spring:
  application:
    name: greeter
    profiles.active: dev
  main:
    allow-bean-definition-overriding: true

## you can comment out all eureka config on TAS
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
