spring:
  application:
    name: my-cloud-native-spring
    profiles.active: dev
  main:
    allow-bean-definition-overriding: true

#  config:
#    #import: optional:configserver:http://localhost:8888
#    #import: configserver:${vcap.services.p-config-server.credentials.uri:http://localhost:8888}
  cloud:
    bootstrap:
      enabled: true
server.port: 8080

## you can comment out all eureka config on TAS
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'

cook.special: "Kim Chi in cloud-native-spring app"