spring:
  application:
    name: cloud-native-spring
  profiles.active: dev
  cloud:
    config:
      uri: ${vcap.services.my-config-server.credentials.uri:http://localhost:8888}
    
server.port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'


cook.special: "Kim Chi in cloud-native-spring app"